version: '3.8'
services:
#  spring-app:
#    build:
#      context: .
#      dockerfile: spring.dockerfile
#    container_name: spring-rest-api
#    ports:
#      - '8000:8000'
#    depends_on:
#      - postgres-db
#    environment:
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#    volumes:
#      - ./bookCollection:/bookCollection:rw
  postgres-db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: 'postgres-14'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarydb
      - PGDATA=/data/postgres-librarydb
    ports:
      - '5432:5432'
    volumes:
      - dbvol:/data/postgres-librarydb
volumes:
  dbvol: null
